# Generated by Django 5.1.6 on 2025-03-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200)),
                ('team_description', models.TextField()),
                ('team_context', models.TextField()),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_description', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Team Info',
                'ordering': ['team_name'],
            },
        ),
    ]
