# Generated by Django 5.1.6 on 2025-03-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_service', models.CharField(max_length=200)),
                ('name_service', models.CharField(max_length=200)),
                ('description_service', models.TextField()),
                ('service_one_name', models.CharField(max_length=200)),
                ('service_one_description', models.TextField()),
                ('service_one_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('service_two_name', models.CharField(max_length=200)),
                ('service_two_description', models.TextField()),
                ('service_two_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('service_three_name', models.CharField(max_length=200)),
                ('service_three_description', models.TextField()),
                ('service_three_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('service_four_name', models.CharField(max_length=200)),
                ('service_four_description', models.TextField()),
                ('service_four_image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Service Info',
                'ordering': ['title_service'],
            },
        ),
    ]
