# Generated by Django 5.1.6 on 2025-03-25 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_employee_homepage_service_delete_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='projects_section_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='projects_section_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services_section_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='services_section_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='team_section_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='team_section_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
