# Generated by Django 5.1.6 on 2025-03-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_homepage_projects_section_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='head_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
