# Generated by Django 5.1.6 on 2025-03-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_homepage_head_title_homepage_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_title', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=250, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Service Page',
            },
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name_plural': 'Home Page'},
        ),
    ]
