# Generated by Django 5.1.6 on 2025-03-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_navbar', models.FileField(blank=True, null=True, upload_to='core/site_settings')),
                ('logo_navbar_alt_data', models.CharField(blank=True, help_text='Add data for increasing SEO performance', max_length=255, null=True)),
                ('logo_footer', models.FileField(blank=True, null=True, upload_to='core/site_settings')),
                ('logo_footer_alt_data', models.CharField(blank=True, help_text='Add data for increasing SEO performance', max_length=255, null=True)),
                ('favicon', models.FileField(blank=True, null=True, upload_to='core/site_settings')),
                ('favicon_alt_data', models.CharField(blank=True, help_text='Add data for increasing SEO performance', max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=17, null=True)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=17, null=True)),
                ('iframe', models.TextField(help_text='Just paste iframe src data from googlemap')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(help_text='Enter phone number starting with the code', max_length=255, null=True)),
                ('fax', models.CharField(help_text='Enter fax number starting with the code', max_length=255, null=True)),
                ('facebook', models.URLField(blank=True, help_text='Enter your facebook url', max_length=255, null=True)),
                ('instagram', models.URLField(blank=True, help_text='Enter your instagram url', max_length=255, null=True)),
                ('twitter', models.URLField(blank=True, help_text='Enter your twitter url', max_length=255, null=True)),
                ('linkedin', models.URLField(blank=True, help_text='Enter your linkedin url', max_length=255, null=True)),
                ('youtube', models.URLField(blank=True, help_text='Enter your youtube url', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'Services'},
        ),
    ]
